import { GoogleConfig } from "../config/GoogleConfig";
import { DeepSeekPrompts } from "../core/DeepSeekPrompts";

export interface SheetColumn {
  name: string;
  required?: boolean;
  defaultValue?: string;
  note?: string;
  headerNote?: string;
  numberFormat?: {
    type: string;
    pattern?: string;
  };
  pixelSize?: number;
}

export interface SheetDefinition {
  name: string;
  columns: SheetColumn[];
  frozenRows?: number;
}

export class SheetsSchema {
  static PostsBaseColumns: SheetColumn[] = [
    {
      name: "*date_marker",
      headerNote: [
        "Маркер календаря и готовности строки.",
        "",
        "Цвета:",
        "красный - дата в прошлом;",
        "зеленый - дата сегодня;",
        "синий - дата в будущем;",
        "фиолетовый - [status=ready], но строка невалидна и не будет опубликована.",
      ].join("\n"),
    },
    {
      name: "post_id",
      required: true,
      note: "Internal unique post id generated by Apps Script before posting.",
      headerNote: [
        "Внутренний ID поста.",
        "",
        "Генерируется автоматически Apps Script.",
        "Основа: date + time + platforms + text + media_ids.",
        "",
        "После публикации или обработки не меняется:",
        "[processing], [posted], [partial], [done]",
        "или уже есть message/post id платформы.",
        "",
        "Вручную обычно не редактировать.",
      ].join("\n"),
    },
    {
      name: "date",
      note: "Post date used by autopost time window.",
      headerNote: [
        "Дата публикации.",
        "",
        "Обязательное поле для автопостинга.",
        "Работает вместе с time.",
        "",
        "ПРИМЕР:",
        "[22.06.2026]",
        "",
        "Если date пустая, строка не публикуется.",
      ].join("\n"),
    },
    {
      name: "time",
      note: "Post time used by autopost time window.",
      headerNote: [
        "Время публикации.",
        "",
        "Обязательное поле для автопостинга.",
        "",
        "ФОРМАТ:",
        "[12:30]",
        "[09:05]",
        "",
        "Если time пустое, строка не публикуется.",
      ].join("\n"),
    },
    {
      name: "platforms",
      required: true,
      note: "telegram. VK/Instagram/Facebook are paused until their publishers are enabled again.",
      headerNote: [
        "Платформы для публикации.",
        "",
        "Обязательное поле для автопостинга.",
        "",
        "Разделители:",
        "точка с запятой, запятая или перенос строки.",
        "",
        "ПРИМЕР:",
        "[Telegram]",
        "",
        "Регистр неважен:",
        "[Telegram] и [telegram] работают одинаково.",
        "",
        "Пробел после разделителя необязателен.",
        "",
        "ЗНАЧЕНИЯ:",
        "[Telegram], [TG], [телеграм]",
        "",
        "Публикуются только включенные и настроенные платформы.",
        "VK/Instagram/Facebook сейчас не создаются в таблице и игнорируются, пока выключены в env.",
      ].join("\n"),
    },
    { name: "info/photo/context" },
    {
      name: "text",
      note: "Source text. Optional when media_ids exists.",
      headerNote: [
        "Исходный текст поста.",
        "",
        "DeepSeek/AI может подготовить текст под конкретную платформу.",
        "",
        "Можно оставить пустым, если заполнен media_ids.",
        "Если text и media_ids пустые, строка не публикуется.",
      ].join("\n"),
    },
    {
      name: "media_ids",
      note: "Resolved through MEDIA.media_id.",
      headerNote: [
        "ID медиа из листа MEDIA, колонка media_id.",
        "",
        "Разделители:",
        "точка с запятой, запятая или перенос строки.",
        "",
        "ПРИМЕР:",
        "[IMG_001; VID_0001]",
        "",
        "Можно оставить пустым, если заполнен text.",
        "Missing/битые медиа пропускаются, остальные медиа и текст публикуются.",
      ].join("\n"),
    },
    { name: "preview_1" },
    { name: "preview_2" },
    { name: "preview_3" },
    { name: "preview_4" },
    { name: "preview_5" },
    { name: "preview_6" },
    { name: "preview_7" },
    { name: "preview_8" },
    { name: "preview_9" },
    { name: "preview_10" },
    {
      name: "status",
      required: true,
      defaultValue: "draft",
      headerNote: [
        "Ручной переключатель автопостинга.",
        "",
        "Публикуется только:",
        "[ready]",
        "",
        "Не публикуются:",
        "[пусто]",
        "[template]",
        "[draft]",
        "",
        "Сервер сам пишет:",
        "[processing] - взял в работу;",
        "[posted] - успешно опубликовано;",
        "[partial] - часть платформ успешна, часть нет;",
        "[error] - ошибка;",
        "[skipped] - пропущено.",
        "",
        "Для повторной попытки вручную поставь [ready].",
      ].join("\n"),
    },
  ];

  static PostsServerColumns: SheetColumn[] = [
    { name: "telegram_status" },
    { name: "telegram_lock_until" },
    { name: "telegram_published_at" },
    { name: "telegram_message_id" },
    { name: "telegram_url" },
    { name: "telegram_error" },
    { name: "telegram_response" },
  ];

  static MediaBaseColumns: SheetColumn[] = [
    { name: "preview" },
    { name: "media_id", required: true },
    { name: "type" },
    { name: "file_status" },
    { name: "path" },
    { name: "name" },
    { name: "drive_url" },
    { name: "file_id" },
    { name: "mime_type" },
    { name: "preview_url" },
    { name: "created_at" },
    { name: "updated_at" },
    { name: "used_count" },
    { name: "posted_count" },
    { name: "last_posted_at" },
    { name: "used_in_posts" },
  ];

  static MediaServerColumns: SheetColumn[] = [
    { name: "public_url", note: "Public HTTPS media URL for Meta posting." },
    { name: "media_url", note: "Direct media URL fallback." },
  ];

  static LeadsColumns: SheetColumn[] = [
    { name: "created_at", required: true },
    { name: "name" },
    {
      name: "phone",
      numberFormat: { type: "TEXT" },
      pixelSize: 170,
      note: "Displayed as +7 999 000-00-00. Server receives raw digits and formats the sheet value.",
    },
    { name: "email" },
    { name: "telegram" },
    { name: "date" },
    { name: "guests" },
    { name: "scenario" },
    { name: "consent" },
    { name: "meta_json" },
  ];

  static LogsColumns: SheetColumn[] = [
    { name: "created_at", required: true },
    { name: "level", required: true },
    { name: "message", required: true },
    { name: "data_json" },
  ];

  static SettingsColumns: SheetColumn[] = [
    {
      name: "key",
      required: true,
      headerNote: [
        "Ключ настройки.",
        "",
        "Менять только если меняется код сервера.",
        "Обычно редактируется только колонка value.",
      ].join("\n"),
    },
    {
      name: "value",
      headerNote: [
        "Значение настройки.",
        "",
        "Для boolean используй:",
        "[true]",
        "[false]",
        "",
        "Регистр неважен, но рекомендуемый формат - маленькими буквами.",
      ].join("\n"),
    },
    {
      name: "description",
      headerNote: [
        "Описание настройки.",
        "",
        "Тут указан формат значения и что настройка меняет.",
        "",
        "ВАЖНО:",
        "если value пустой, сервер использует default из кода/env.",
      ].join("\n"),
    },
    {
      name: "value_ru",
      headerNote: [
        "Русская версия значения или промпта.",
        "",
        "Сервер это поле не читает.",
        "Поле нужно, чтобы понимать смысл английского prompt/value.",
      ].join("\n"),
    },
  ];

  static SettingsDefaults = [
    [
      "autopost.enabled",
      "false",
      [
        "Включает автопостинг из Google таблицы.",
        "",
        "ФОРМАТ VALUE:",
        "[true] - включить;",
        "[false] - выключить.",
        "",
        "Регистр неважен, но лучше писать маленькими буквами.",
        "",
        "Важно:",
        "env AUTOPOST_ENABLED тоже должен быть true.",
        "Если env выключен, значение в таблице не запустит worker.",
        "",
        "Если value пустой:",
        "берётся default текущего сервера из env.",
      ].join("\n"),
      "",
    ],
    [
      "autopost.interval_ms",
      "60000",
      [
        "Частота проверки новых постов.",
        "",
        "ФОРМАТ VALUE:",
        "число в миллисекундах.",
        "",
        "ПРИМЕРЫ:",
        "[60000] = 1 минута;",
        "[300000] = 5 минут.",
        "",
        "Рекомендуемо для продакшена:",
        "[60000] или больше.",
        "",
        "Если value пустой:",
        "берётся default текущего сервера из env.",
      ].join("\n"),
      "",
    ],
    [
      "autopost.publish_window_minutes",
      "180",
      [
        "Окно публикации назад.",
        "",
        "ФОРМАТ VALUE:",
        "число в минутах.",
        "",
        "Что значит:",
        "если сервер был выключен, он может выпустить пропущенный ready-пост",
        "в течение этого количества минут после date + time.",
        "",
        "ПРИМЕР:",
        "[180] = можно публиковать в течение 3 часов после планового времени.",
        "",
        "Если value пустой:",
        "берётся default текущего сервера из env.",
      ].join("\n"),
      "",
    ],
    [
      "autopost.future_grace_seconds",
      "30",
      [
        "Небольшой допуск вперед.",
        "",
        "ФОРМАТ VALUE:",
        "число в секундах.",
        "",
        "Что значит:",
        "сервер может взять пост чуть раньше точного времени,",
        "чтобы не пропустить пограничную секунду проверки.",
        "",
        "ПРИМЕР:",
        "[30] = допуск 30 секунд вперед.",
        "",
        "Если value пустой:",
        "берётся default текущего сервера из env.",
      ].join("\n"),
      "",
    ],
    [
      "deepseek.enabled",
      "true",
      [
        "Включает подготовку текста через DeepSeek.",
        "",
        "ФОРМАТ VALUE:",
        "[true] - включить;",
        "[false] - выключить.",
        "",
        "Регистр неважен, но лучше писать маленькими буквами.",
        "",
        "ВАЖНО:",
        "env DEEPSEEK_ENABLED тоже должен быть true.",
        "Если env выключен, значение в таблице не включит DeepSeek.",
        "",
        "Если value пустой:",
        "берётся default текущего сервера из env.",
        "",
        "Если выключено:",
        "автопостинг использует исходный текст/fallback и не падает.",
      ].join("\n"),
      "",
    ],
    [
      "deepseek.telegram.prompt",
      DeepSeekPrompts.TELEGRAM_EN,
      [
        "Рабочий prompt для подготовки Telegram-текста через DeepSeek.",
        "",
        "ФОРМАТ VALUE:",
        "английский prompt, который сервер отправляет в DeepSeek.",
        "",
        "Доступная переменная:",
        "[{{telegram_limit}}] - лимит символов для Telegram.",
        "",
        "ВАЖНО:",
        "если value пустой, сервер использует default Telegram prompt из кода.",
        "",
        "value_ru:",
        "русская версия prompt для понимания смысла и редактирования.",
      ].join("\n"),
      DeepSeekPrompts.TELEGRAM_RU,
    ],
  ];

  static Definitions(): SheetDefinition[] {
    return [
      {
        name: GoogleConfig.POSTS_SHEET,
        frozenRows: 1,
        columns: [...this.PostsBaseColumns, ...this.PostsServerColumns],
      },
      {
        name: GoogleConfig.MEDIA_SHEET,
        frozenRows: 1,
        columns: [...this.MediaBaseColumns, ...this.MediaServerColumns],
      },
      {
        name: GoogleConfig.LEADS_SHEET,
        frozenRows: 1,
        columns: this.LeadsColumns,
      },
      {
        name: GoogleConfig.LOGS_SHEET,
        frozenRows: 1,
        columns: this.LogsColumns,
      },
      {
        name: GoogleConfig.SETTINGS_SHEET,
        frozenRows: 1,
        columns: this.SettingsColumns,
      },
    ];
  }
}
